services:
  # server:
  #   build: .
  #   container_name: compressor
  #   ports:
  #     - "3010:3010"
  #   depends_on:
  #     - minio
  minio:
    image: minio/minio
    volumes:
      - ./data/minio:/data
    ports:
      - '9001:9001'
      - '9000:9000'
    env_file:
      - .env
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    command: server --console-address ":9001" /data
