services:
  minio:
    image: minio/minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    env_file:
      - .env
    command: server --console-address ":9001" /data
